services:
  mysql:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      #MYSQL_USER: ${MYSQL_USER}
      #MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - pyspark-network
    tmpfs:
      - /var/lib/mysql

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile  # Utilisation du Dockerfile personnalisé situé à la racine
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
    networks:
      - pyspark-network
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8080:80"  # Exposer phpMyAdmin sur le port 8080
    depends_on:
      - mysql
    networks:
      - pyspark-network

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE}
      - SONARQUBE_JDBC_USERNAME=${PMA_USER}
      - SONARQUBE_JDBC_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SONARQUBE_ADMIN_PASSWORD=${PMA_PASSWORD}
    ports:
      - "9000:9000"
    networks:
      - pyspark-network
    depends_on:
      - mysql

networks:
  pyspark-network:
    driver: bridge

volumes:
  db_data:
